version: '3.9'

services:
  web:
    build: .
    container_name: leilao_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./oracle_wallet:/app/oracle_wallet
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TNS_ADMIN=oracle_wallet
